version: '3.2'

networks:
  stark_network:
    driver: bridge

services:

  ##################################################
  ######                NGINX                #######
  ##################################################

  stark_nginx:
    build: ./images/nginx
    container_name: stark_nginx
    ports:
      - 80:80
      - 8000:80
    command: dc_init_command
    expose:
      - 8001
    volumes:
      - ./data:/data
      - ./logs/nginx:/var/log/nginx
      - ./resources/nginx/dc_command.sh:/usr/bin/dc_command
      - ./resources/nginx/dc_init_command.sh:/usr/bin/dc_init_command
      - ./resources/nginx/sites-available:/etc/nginx/sites-available/sites-available
    depends_on:
      - stark_redis
      - stark_mysql
      - stark_back
      - stark_front

    networks:
      stark_network:
        aliases:
          - stark.local
          - api.stark.local

  ##################################################
  ######                REDIS                #######
  ##################################################

  stark_redis:
    image: redis:alpine
    container_name: stark_redis
    ports:
      - "16379:6379"
    command: >
      --requirepass Qazxsw123
    networks:
      - stark_network

  ##################################################
  ######                MYSQL                #######
  ##################################################

  stark_mysql:
    image: mysql/mysql-server:8.0
    container_name: stark_mysql
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./resources/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Qazxsw123
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: user
      MYSQL_PASSWORD: Qazxsw123
    cap_add:
      - SYS_NICE
    restart: always
    networks:
      - stark_network

  ##################################################
  ######                BACK                 #######
  ##################################################

  stark_back:
    build: ./images/php8
    container_name: stark_back
    expose:
      - 9000
    links:
      - stark_mysql
      - stark_redis
    command: dc_init_command
    volumes:
      - ./data/back:/data/back
      - ./resources:/resources
      - ./resources/back/dc_command.sh:/usr/bin/dc_command
      - ./resources/back/dc_init_command.sh:/usr/bin/dc_init_command
    restart: always
    working_dir: /data/back
    networks:
      - stark_network

  stark_events:
    build: ./images/php8
    expose:
      - 9000
    links:
      - stark_mysql
      - stark_redis
    command: php artisan queue:work --queue=events
    volumes:
      - ./data/back:/data/back
      - ./resources:/resources
    restart: always
    working_dir: /data/back
    networks:
      - stark_network

  stark_rawg:
    build: ./images/php8
    expose:
      - 9000
    links:
      - stark_mysql
      - stark_redis
    command: php artisan queue:work --queue=rawg
    volumes:
      - ./data/back:/data/back
      - ./resources:/resources
    restart: always
#    deploy:
#      mode: replicated
#      replicas: 10
    working_dir: /data/back
    networks:
      - stark_network

  stark_steam:
    build: ./images/php8
    expose:
      - 9000
    links:
      - stark_mysql
      - stark_redis
    command: php artisan queue:work --queue=steam
    volumes:
      - ./data/back:/data/back
      - ./resources:/resources
    restart: always
#    deploy:
#      mode: replicated
#      replicas: 5
    working_dir: /data/back
    networks:
      - stark_network

  ##################################################
  ######                FRONT                #######
  ##################################################

  stark_front:
    build: ./images/front
    container_name: stark_front
    expose:
      - 3000
    links:
      - stark_mysql
    command: dc_init_command
    volumes:
      - ./data/front:/data/front
      - ./resources:/resources
      - ./resources/front/dc_command.sh:/usr/bin/dc_command
      - ./resources/front/dc_init_command.sh:/usr/bin/dc_init_command
    restart: always
    working_dir: /data/front
    networks:
      - stark_network
